n1sp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('theapp.urls')),
    url(r'^$', RedirectView.as_view(url='/users/home'))
]

theapp/urls.py
from django.conf.urls import url

from theapp import views
urlpatterns = [

    url(r'^notif$', views.omnitest, name='omnibus'),

    url(r'^signup$', views.signup, name='signup'),

    url(r'^login$', views.user_login, name='login'),
    url(r'^logout$', views.user_logout, name='logout'),

    url(r'^send-confirmation$', views.generate_confirmation,
        name='send-confirmation-email'),

    url(r'^approve/(?P<user_id>\d+)$',
        views.approve_user, name='approve-user'),
    url(r'^approvals$',
        views.approvals, name='approvals'),

    url(r'^email-confirm/(?P<token>[a-zA-Z0-9]+)$',
        views.confirm_email, name='email-confirm'),

    url(r'', views.user_home, name='user-home'),

    # url(r'^signup$', admin.site.urls),
]

theapp/models/approval.py
from django.db import models
from django.contrib.auth.models import Group

from rulez import registry

from .user import User
from theapp.predefined import ADMIN_TYPE_TWO, ADMIN_TYPE_ONE


class Approval(models.Model):
    """
    Approval of a user by an admin.
    """

    APPROVAL_CHOICES = (
        ('A', 'Approved'),
        ('P', 'Pending'),
        ('R', 'Rejected')
    )
    for_user = models.ForeignKey(User, related_name='approvals')
    by_admin = models.ForeignKey(User)
    admin_type = models.ForeignKey(Group)
    approval = models.CharField(max_length=1, choices=APPROVAL_CHOICES,
                                default='P')
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """
        Should read like:

        <username> (admin-level-x) has approved <for_user>
        """
        done = " has approved "
        pending = "'s approval for "
        middle = [pending, done][self.approval == 'A']
        representation = self.admin_type.name + self.by_admin.username \
            + middle + self.for_user.username
        return representation

    def can_be_approved_by(self, user_obj):
        '''
        Returns a bool, depending on whether
        the acting admin/user CAN approve the
        user, given the requirements of business logic.
        '''

        # ADMIN TYPE 2 can approve ALL
        if user_obj.groups.filter(name=ADMIN_TYPE_TWO).exists():
            return True

        # ADMIN TYPE 1 users from his city only
        if user_obj.groups.filter(name=ADMIN_TYPE_ONE).exists():
            if user_obj.location == self.for_user.location:
                return True

        # Not an admin
        # OR, admin is type 1, and user is not in his location
        return False

    def mark_approved(self):
        self.approval = 'A'
        self.save()

registry.register('can_be_approved_by', Approval)

theapp/models/city.py
from django.db import models


class City(models.Model):
    """
    Location model - store some locales
    """
    name = models.CharField(max_length=1024)

    def __str__(self):
        return self.name

theapp/models/email_verification.py
from django.db import models
from django.utils.crypto import hashlib
from django.utils import timezone

from .user import User


class EmailVerification(models.Model):
    """
    Simple replacement for an otherwise
    more mature allauth's emailaddress model.
    """
    user = models.ForeignKey(User)
    token = models.CharField(max_length=100)
    verified = models.BooleanField(default=False)

    # def __init__(self, *args, **kwargs):
    #     self.token = self.create_token()
    #     super(EmailVerification, self).__init__(args, kwargs)

    def create_token(self):
        val = (str(timezone.now()) + self.user.email).encode('utf-8')
        return hashlib.sha256(val).hexdigest()

    def confirm(self):
        self.email_verified = True
        self.save()

    def __str__(self):
        return self.user.email

theapp/models/notification.py
from django.db import models
from .user import User
from .approval import Approval


class Notification(models.Model):
    """
    A very dumbed down, this app
    specific notification model
    describing an actor acting out a verb.

    Not using GFKs to use it for any type of
    models for actors, actions, and targets.

    actor  -  Person who took some action
    verb   -  Describing the action taken
    action -  Action model that stores a record of action
    target -  Person affected or involved in action
    user   -  Person who gets notified

    Basically, something like this:
    <actor> <verb>AND/OR<action> <target>

    Examples:
    <actor> <verb> <target>
    Jack approved John

    <actor> <verb> <action>
    Jack reached level-3

    <actor> <verb> <action> <target>
    Rimi started following Jackie
    """

    # The person who gets notified
    receiver = models.ForeignKey(User, related_name='notification_receiver')

    # The approval for which the notification is created
    approval = models.ForeignKey(Approval, related_name='actor')

    is_read = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)

theapp/models/user.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .city import City


class User(AbstractUser):
    """
    Custom user model,
    with one additional field: `location`
    """

    location = models.ForeignKey(City)

theapp/forms.py
from django.forms import ModelForm
from theapp.models import User, City


class UserForm(ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'location']

    # def __init__(self, *args, **kwargs):
    #     super(UserForm, self).__init__(*args, **kwargs)
    #     self.fields['city'].queryset = City.objects.all()
        # assuming your Category model has user foreignkey/onetone field.

theapp/views.py
import traceback

from django.shortcuts import render
from django.http import HttpResponse
from django.views.decorators.http import require_http_methods
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from django.core.urlresolvers import reverse
from django.db.models import Q

from theapp.models import EmailVerification
from theapp.models import User
from theapp.models import Approval
from theapp.tasks import post_signup_processing, send_email_confirmation
from theapp.forms import UserForm
from theapp.predefined import ADMIN_TYPE_ONE
from theapp.predefined import ADMIN_TYPE_TWO


def omnitest(request):
    return render(request, 'theapp/omni_frontend.html')


def signup(request):
    if request.method == 'GET':
        form = UserForm()
        return render(request, "theapp/signup.html",
                      {'form': form})
    else:
        form = UserForm(request.POST or None)
        if form.is_valid():
            user = form.save()
            user.set_password(form.data['password'])
            user.save()
            post_signup_processing.delay(user, request.get_host())
            return render(request, 'theapp/signup.html', {'ok': user})
        else:
            return render(request, "theapp/signup.html",
                          {'form': form})


@require_http_methods(["GET"])
def approvals(request):
    if not request.user.is_authenticated():
        return redirect(reverse('login'))

    is_admin = Q(name=ADMIN_TYPE_ONE) | Q(name=ADMIN_TYPE_TWO)
    if not request.user.groups.filter(is_admin).exists():
        return HttpResponse("You are not an admin", status_code=403)

    approvals = Approval.objects.filter(by_admin=request.user)
    return render(request, 'theapp/admin_approvals.html',
                  dict(approvals=approvals))


@require_http_methods(["GET"])
def approve_user(request, user_id):
    is_admin = Q(name=ADMIN_TYPE_ONE) | Q(name=ADMIN_TYPE_TWO)
    message = ''
    if request.user.groups.filter(is_admin).exists():
        try:
            user = User.objects.get(pk=user_id)
        except:
            return HttpResponse("User does not exist")
        else:
            approval = user.approvals.filter(by_admin=request.user).first()
            if approval is None:
                message = "You are not authorized to approve this user."
            else:
                if approval and approval.can_be_approved_by(request.user):
                    approval.mark_approved()
                    message = "Approved %s !" % user.username
                else:
                    message = "You are not authorized to approve this user."
    else:
        message = "Only admins can approve."

    return HttpResponse(message)


@require_http_methods(["GET", "POST"])
def user_logout(request):
    """
    Logout user.
    """
    logout(request)
    return redirect(reverse('login'))


@require_http_methods(["GET", "POST"])
def user_login(request):
    """
    View a user sees when they login,
    or after clicking an email confirmation
    link.
    """
    if request.user and request.user.is_authenticated():
        return redirect(reverse('user-home'))
    data = request.POST
    # user_id can be either via username or email
    user_id = data.get('username', None)
    password = data.get('password', None)

    # Try to authenticate a user with given creds
    user = authenticate(username=user_id, password=password)
    if not user:
        error = "Incorrect password or username."
        print(error)
        return render(request,
                      'theapp/login.html',
                      dict(error=error))

    try:
        # Login user
        login(request, user)
    except:
        traceback.print_exc()
        return render(request,
                      'theapp/login.html',
                      error='Something went wrong. Sorry.')
    else:
        return redirect(reverse('user-home'))


@require_http_methods(["GET"])
def user_home(request):
    """
    View a user sees if they are logged in,
    or after clicking an email confirmation
    link.
    """

    if not request.user.is_authenticated():
        return redirect(reverse('login'))

    errors = []

    # Check if user has confirmed their email
    email_address = EmailVerification.objects.filter(
        user=request.user).first()

    # A message, in case they haven't.
    if not email_address or not email_address.verified:
        errors.append('Your email is not verified yet. ')
        errors.append('Please click the activation link in your email.')
        return render(request, 'theapp/user_home.html',
                      {'not_verified': True, 'errors': errors})

    approvals = Approval.objects.filter(for_user=request.user)
    # A successful logged in user will see this
    return render(request,
                  'theapp/user_home.html',
                  {'approvals': approvals})


@require_http_methods(["GET"])
def generate_confirmation(request):
    if request.user.is_authenticated():
        send_email_confirmation(request.user)
    return redirect(reverse('login'))


@require_http_methods(["GET"])
def confirm_email(request, token):
    message = ''
    if EmailVerification.objects.filter(token=token).exists():
        email = EmailVerification.objects.filter(token=token).first()
        if not email.verified:
            email.verified = True
            email.user.is_active = True
            email.save()
            email.user.save()
            message = "Thank you for verifying your email.\
                        You now need to wait for your approval."
        else:
            message = "You've already confirmed your email."

    else:
        message = "Invalid confirmation token. Please contact site admin."

    return render(request, "theapp/verified.html", dict(message=message))

theapp/templates/theapp/admin_approvals.html
{% extends "theapp/base.html" %}
{% load rulez_perms %}
{% load can_approve %}

{% block title %} Approvals {% endblock %}
{% block content %}

<style>
th {
    background-color: rgba(41, 127, 237, 0.86);
    color: white;
}
th, td {
    padding: 15px;
    text-align: center;
}
tr:hover {background-color: #f5f5f5}

</style>
<!-- JS for 'approve' button to send AJAX GET -->
<script>

function approve_user(url, pk){

		var element = "approval_container_" + pk;
		console.log("Element formed: "+element);
        $.get(url, function(data, status){
        	document.getElementById(element).innerHTML = data;
            $(element).html(data);
            console.log(data);
        });
}
</script>


<div style='padding-left:45%;'>
	<h3> Approvals </h3>
</div>

Here are the users and their approval statuses:
<br>
<br>
	<table border=1 bordercolor="#00CCFF";>
		<th style='width:100px;'>User</th> <th style='width:100px;'>Status</th> <th style='width:200px;'>Action</th>
		{% for approval in approvals %}
		<tr>
			<td style='text-align:center'>
				{{ approval.for_user.username }}
			</td>
			<td style='text-align:center'>
				{{ approval.get_approval_display }}	
			</td>
			<td style='text-align:center'>
			{% can_approve request.user approval as show %}
				{% if show and approval.approval == 'P' %}
					<div id="approval_container_{{approval.pk}}">
					<input type="button" id="approval_button"
					value='Approve'
					onClick="approve_user('{% url 'approve-user' approval.for_user.pk %}',
					'{{approval.pk}}')"
					/>
					</div>
				{% elif approval.approval == 'A' %}
				Approved
				{% else %}
				User not in your location
				{% endif %}
			</td>
		</tr>
	{% endfor %}
	</table>

{% endblock %}

theapp/templates/theapp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	
	{% block extrahead %}{% endblock %}
</head>
<body>
	<div>	
		{% if request.user.is_authenticated %}
			<p style="float:left">
				Hi, {{ request.user.get_full_name|default:request.user.username }}	
			</p>

			<p style="float:left; margin-left:10px;">
				<a href="{% url 'logout' %}">Logout</a>
			</p>
		{% else %}
			You are not logged in
			<br>
			<a href="{% url 'login' %}">Login</a>
			<a href="{% url 'signup' %}">Signup</a>
		{% endif %}
		<br>
	</div>


<script type="text/javascript" src="{% static 'omnibus/omnibus.js' %}"></script>

{% if request.user.is_authenticated %}
	<script type="text/javascript">
	(function () {

	// Select a transport implementation:
	var transport = WebSocket; // SockJS can be used alternatively

	// Receive the path for the connection from the django template context:
	var endpoint = '{{ OMNIBUS_ENDPOINT }}';

	var options = {authToken: '{{ OMNIBUS_AUTH_TOKEN }}'};
	var connection = new Omnibus(transport, endpoint, options);

	var channel = connection.openChannel('{{ request.user.pk }}');
	// Add events on channel:
	channel.on('approval', function (event) {
			$("#notification").append(event.data.payload.message + '<br>');
			$("#notification-time").append(event.data.payload.timestamp + '<br>');
	});
	}
	)();
	</script>
	<div id='notif' style="float:right; width: auto; rgba(131, 179, 220, 0.15);">
		<p>Notifications</p>
		<br>
		<span style="font-size: x-small;">
		<p style='float:left; margin-right:5px;' id='notification'></p>
		<p id='notification-time'></p>
		</span>
	</div>

{% endif %}

{% block header %} {% endblock %}
{% block content %} {% endblock %}
{% block footer %} {% endblock %}
</body>
</html>

theapp/templates/theapp/login.html
{% extends "theapp/base.html" %}

{% block title %} Login {% endblock %}

{% block content %}

<h2> Login </h2>

{% if error %}
{{ error }}
{% endif %}
<form method='POST'>
{% csrf_token %}
<ul>
	<input type=text name='username'/>	
</ul>
<ul>	
	<input type=password name='password'/>
</ul>
<ul>
	<input type=submit value="Login"/>
</ul>
</form>

{% endblock %}

theapp/templates/theapp/omni_frontend.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Notification testing</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
</head>
<body>

<script type="text/javascript" src="{% static 'omnibus/omnibus.js' %}"></script>


<script type="text/javascript">
(function () {

// Select a transport implementation:
var transport = WebSocket; // SockJS can be used alternatively

// Receive the path for the connection from the django template context:
var endpoint = '{{ OMNIBUS_ENDPOINT }}';

var options = {authToken: '{{ OMNIBUS_AUTH_TOKEN }}'};
var connection = new Omnibus(transport, endpoint, options);

var channel = connection.openChannel('test-channel');
// Add events on channel:
channel.on('myevent', function (event) {
		$("#notification").append(event.data.payload.message + '<br>');
		$("#notification-time").append(event.data.payload.timestamp + '<br>');
});
}
)();
</script>


See the notification here:
<br>
============
<div>
	<p style='float:left; margin-right: margin-right:50px;' id='notification'></p> <p style='float:left;' id='notification-time'></p>
</div>

============
</body>
</html>

theapp/templates/theapp/signup.html
{% extends "theapp/base.html" %}

{% block title %} Signup {% endblock %}

{% block content %}

<h2> Signup </h2>

{% if ok %}

Signup completed successfully, {{ ok.username }}
ID: {{ ok.id }}

{% else %}

<form method='POST'>
{% csrf_token %}
{{ form.as_p }}
<input type=submit value="Signup"/>
</form>

{% endif %}

{% endblock %}

theapp/templates/theapp/user_home.html
{% extends "theapp/base.html" %}
{% load static %}

{% block title %} Home {% endblock %}

{% block content %}

<div style='padding-left:45%;'>
	<h3> Home </h3>
</div>

{% if request.session.message %}
{{ request.session.message }}
{% endif %}

{# If logged in, but email not verified #}
{% if not_verified %}

	<p>
		{% for error in errors %}
			<ul>{{ error }}</ul>
		{% endfor %}
	</p>

	<a href="{% url 'send-confirmation-email' %}">
		Click here to send a confirmation mail again.
	</a>

{% else %}
<hr>
{% if request.user.is_staff %}
<a href="{% url 'approvals' %}">Check users awaiting approval</a>
{% else %}

Here are your approvals:

	{% for approval in approvals %}
		<ul>
			{{ approval.admin_type.name }} - {{ approval.get_approval_display }}
		</ul>
	{% endfor %}
{% endif %}
{% endif %}

{% endblock %}

theapp/templates/theapp/verified.html
{% extends "theapp/base.html" %}

{% block title %} Verified {% endblock %}

{% block content %}

<h2> Email verified </h2>

{{ message }}
{% endblock %}